version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"
    resource_class: medium+
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# commands:
#   report-coverage:
#     description: |
#       Store coverage report as an artifact and send it to Codecov service.
#     steps:
#       - store_artifacts:
#           path: coverage
#       - run: npx nyc report --reporter=text || true
#       - codecov/upload:
#           file: coverage/coverage-final.json

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
  cypress-test:
    jobs:
      # Setup
      #  1. Install Cypress
      #  2. Validate types
      #  3. Run server unit-tests
      # Run E2E tests in Chrome
      - cypress/run:
          yarn: true
          browser: chrome
          config-file: cypress.json
          spec: cypress/integration/demo/**/*
          filters:
            branches:
              only:
                - circleci-project-setup
          executor: with-chrome-and-firefox
          wait-on: 'http://localhost:3000'
          command-prefix: yarn
          start: yarn start
          # record: true
          # parallel: true
          # parallelism: 5
          # ci-build-id: ${CIRCLE_SHA1:0:8}
          # group: "UI - Chrome"
          # post-steps:
          #   - report-coverage

      # # Run E2E tests in Chrome with mobile device viewport
      # - cypress/run:
      #     name: "UI Tests - Chrome - Mobile"
      #     browser: chrome
      #     spec: cypress/tests/ui/*
      #     config: "viewportWidth=375,viewportHeight=667"
      #     executor: with-chrome-and-firefox
      #     wait-on: "http://localhost:3000"
      #     yarn: true
      #     start: yarn start:ci
      #     record: true
      #     parallel: true
      #     parallelism: 5
      #     ci-build-id: ${CIRCLE_SHA1:0:8}
      #     group: "UI - Chrome - Mobile"
      #     requires:
      #       - Setup Linux
      #     # post-steps:
      #     #   - report-coverage

      # # Run E2E tests in Firefox
      # - cypress/run:
      #     name: "UI Tests - Firefox"
      #     browser: firefox
      #     spec: cypress/tests/ui/*
      #     executor: with-chrome-and-firefox
      #     wait-on: "http://localhost:3000"
      #     yarn: true
      #     start: yarn start:ci
      #     record: true
      #     parallel: true
      #     parallelism: 5
      #     ci-build-id: ${CIRCLE_SHA1:0:8}
      #     group: "UI - Firefox"
      #     requires:
      #       - Setup Linux
      #     post-steps:
      #       - report-coverage

      # # Run E2E tests in Firefox with mobile device viewport
      # - cypress/run:
      #     name: "UI Tests - Firefox - Mobile"
      #     browser: firefox
      #     spec: cypress/tests/ui/*
      #     config: viewportWidth=375,viewportHeight=667
      #     executor: with-chrome-and-firefox
      #     wait-on: "http://localhost:3000"
      #     yarn: true
      #     start: yarn start:ci
      #     record: true
      #     parallel: true
      #     parallelism: 5
      #     ci-build-id: ${CIRCLE_SHA1:0:8}
      #     group: "UI - Firefox - Mobile"
      #     requires:
      #       - Setup Linux
      #     post-steps:
      #       - report-coverage