name: E2E in custom container
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn start
          config-file: cypress.json
          spec: cypress/integration/demo/**/*
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: cypress/screenshots
        if: ${{ failure() }}