name: End-to-end tests
on: 
  push:
    branches: [ branch2 ]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure our "app" works on several versions of Node
    strategy:
      matrix:
        node: [14.17.0]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-dep-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup Yarn dep cache
        uses: actions/cache@v2
        id: yarn-dep-cache
        with:
            path: ${{ steps.yarn-dep-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-dep-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                ${{ runner.os }}-yarn-dep-
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # caching yarn depenedencies: https://stackoverflow.com/questions/61010294/how-to-cache-yarn-packages-in-github-actions/62244232#62244232
          cache: 'yarn'
      - name: Yarn install deps
        run: yarn
      # run Cypress tests and record them under the same run
      # associated with commit SHA and just give a different group name
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          # record: true
          # group: Tests on Node v${{ matrix.node }}
          # cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
          ### https://github.com/cypress-io/github-action/issues/489#issuecomment-1021379037 ###
          start: yarn start
          command-prefix: "--"
          config-file: cypress.json
          spec: cypress/integration/demo/**/*